### ISSUE TITLE
0.3.0 works with command line, but fails with IDEA test run

### ISSUE THREAD

**Issue by blindpirate** [bnorm/kotlin-power-assert#12]
build.gradle.kts:

```
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.70"
    id("com.bnorm.power.kotlin-power-assert") version "0.3.0"
}

tasks.named("compileTestKotlin", KotlinCompile::class.java) {
    // https://github.com/bnorm/kotlin-power-assert
    kotlinOptions {
        useIR = true
    }
}
```

It works fine with command line `./gradlew test` (latest 6.2.2), but fails if you right-click the test class and run in IDEA.

```
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
Licensed to Gogradle / Bo Zhang
Subscription is active until May 20, 2020
For non-commercial open source development only.
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false, js.debugger.webconsole=false
Non-Bundled Plugins: ASM Bytecode Outline, ASM Bytecode Viewer, Builder Generator, EclipseCodeFormatter, FindBugs-IDEA, GsonFormat, IdeaVIM, JProfiler, Jetbrains TeamCity Plugin, Lombook Plugin, MavenRunHelper, Statistic, com.webschik.doT, com.yiycf.plugins.mavenDependencyHelper, izhangzhihao.rainbow.brackets, jclasslib, jd-intellij, mobi.hsz.idea.gitignore, org.antlr.intellij.plugin, org.asciidoctor.intellij.asciidoc, org.exbin.deltahex.intellij, org.jetbrains.idea.grammar, training, wu.seal.tool.jsontokotlin
```

```
Error:Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin com.bnorm.power.PowerAssertComponentRegistrar is not compatible with this version of compiler
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:606)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:135)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:175)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:422)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:263)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1479)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AbstractMethodError: Receiver class com.bnorm.power.PowerAssertComponentRegistrar does not define or inherit an implementation of the resolved method 'abstract void registerProjectComponents(com.intellij.mock.MockProject, org.jetbrains.kotlin.config.CompilerConfiguration)' of interface org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:598)
	... 27 more
```

See here for the reproduction example:

https://github.com/blindpirate/gradle-bot/blob/power-assert-issue/src/test/kotlin/org/gradle/bot/eventhandlers/teamcity/UpdateCIStatusForAllOpenPullRequestsTest.kt

![image](https://user-images.githubusercontent.com/12689835/78092703-fd7ff700-7402-11ea-87be-55d5fc93e4f7.png)

**Comment by bnorm** [comment]
From the reproduction it looks like you are using IntelliJ to compile the project and it is using Kotlin 1.3.61 even though 1.3.70 is specified in the Gradle file. I'm not sure what would be causing that disparity but I would recommend making sure you have the latest Kotlin plugin.

Ultimately I would recommend going to IntelliJ settings > Gradle for your project and select building and running using Gradle rather than IntelliJ.

**Comment by blindpirate** [comment]
You're right, updating kotlin plugin to 1.3.71 solves the problem. Thank you for the quick reply.
