### ISSUE TITLE
Compiler with the plugin fails with an exception on anonymous object comparing

### ISSUE THREAD

**Issue by petukhovv** [bnorm/kotlin-power-assert#77]
The code is:
```
assert(object {  }.toString() == "foo")
```
The exception:
~~~
The root cause java.lang.AssertionError was thrown at: org.jetbrains.kotlin.backend.jvm.lower.AnonymousObjectSuperConstructorLowering.visitBlock(AnonymousObjectSuperConstructorLowering.kt:70)
...
Caused by: java.lang.AssertionError: object literal does not end in a constructor call
	at org.jetbrains.kotlin.backend.jvm.lower.AnonymousObjectSuperConstructorLowering.visitBlock(AnonymousObjectSuperConstructorLowering.kt:70)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:170)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
~~~

**Comment by TWiStErRob** [comment]
Nice one! I'm really curious what is your use case that triggered this finding.

**Comment by petukhovv** [comment]
Actually, I'm engaged into development of another power assertion (not for Kotlin) and tried playing with this one :)
